[General]
debug = True
log_level = info
[Database]
db_collection = PromptDB
db_table = sample_prompt
db_host = 192.168.10.115
db_port = 19530
[Ollama]
; host = http://192.168.10.109:11434/api/
host = https://ollama.plintus.uk/api/
port = 11434
model = NPOAssistant
; model = llama3.2